services:

  milter:
    build: .
    env_file:
      - .env.local
    depends_on:
      - redis

  postfix-relay:
    image: mwader/postfix-relay:latest
    env_file:
      - .env.local
    ports:
      - 25:25
    depends_on:
      - milter

  redis:
    image: redis:7.2-alpine
